# Homebrew PHP CLI
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

# bash autocompletion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

# Lang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export BASH_SILENCE_DEPRECATION_WARNING=1
export LDFLAGS="-L/usr/local/opt/libffi/lib"
LANG=en_US.utf-8
LC_ALL=en_US.utf-8

# Start ssh agent and add all private keys found in ~/.ssh/
addsshkeys () {
  eval `ssh-agent` && find ~/.ssh/ -name "id_rsa" | xargs ssh-add
}

# Add git to terminal
source /usr/local/etc/bash_completion.d/git-completion.bash


# Add git to terminal
source /usr/local/etc/bash_completion.d/git-completion.bash

export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] '

export GIT_PS1_SHOWDIRTYSTATE=1
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export TERM=xterm-256color

# Aliases
alias p='cd ..'
alias ls='ls -GFh'
alias ll='ls -l'

alias hosts='sudo vim /etc/hosts'

alias port80='sudo lsof -i :80'

alias brc='sudo vim ~/.bash_profile'
alias sourceBashrc='source ~/.bash_profile'

alias vol='open /Volumes'

alias brewUpdateAll='brew update; brew upgrade; brew upgrade --cask; brew cleanup;'

# ssh-keys
alias mySSHKey='cat ~/.ssh/id_rsa.pub'
alias sshconfig='vim ~/.ssh/config'

alias insomnia="open -n -a 'insomnia'"